services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nest-url-shortener
    networks:
      - internal
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-nest_user}
      - DB_PASSWORD=${DB_PASSWORD:-nest_password}
      - DB_NAME=${DB_NAME:-url_shortener}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    depends_on:
      - mysql
      - postgres
    restart: always
    volumes:
      - ./database.sqlite:/app/database.sqlite

  mysql:
    image: mysql:8.0
    container_name: nest-mysql
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=url_shortener
      - MYSQL_USER=nest_user
      - MYSQL_PASSWORD=nest_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  postgres:
    image: postgres:15
    container_name: nest-postgres
    networks:
      - internal
    environment:
      - POSTGRES_DB=url_shortener
      - POSTGRES_USER=nest_user
      - POSTGRES_PASSWORD=nest_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
